#!/usr/bin/env python
# -*- encoding: utf-8 -*-


from pyspider.libs.base_handler import *
import pymongo



class Handler(BaseHandler):
    crawl_config = {
        'itag': 'v001'
    }

    client = pymongo.MongoClient("localhost")
    db = client["trip"]

    #@every(minutes=24 * 60)
    def on_start(self):
        self.crawl('https://www.tripadvisor.cn/Attractions-g186338-Activities-London_England.html', callback=self.index_page)

    #@config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('#ATTR_ENTRY_ .listing_title a').items():
            self.crawl(each.attr.href, callback=self.detail_page)

        next_page = response.doc(".pagination a:nth-child(2)").attr.href
        self.crawl(next_page, callback=self.index_page)

    @config(priority=2)
    def detail_page(self, response):
        name = response.doc('#HEADING').text()
        rating = response.doc('.rating_and_popularity .header_popularity span').text()
        comment_count = response.doc('.rating_and_popularity .more span').text()
        address = response.doc('.detail_section.address').text()
        return {
            "name": name,
            "rating": rating,
            "comment_count": comment_count,
            "address": address
        }

    def on_result(self, result):
        if result:
            self.save_to_mongo(result)

    def save_to_mongo(self, result):
        if self.db["landon"].insert(result):
            print("saved in db success:",result)
