#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2018-04-08 23:52:55
# Project: taobaoMM

from pyspider.libs.base_handler import *


class Handler(BaseHandler):
    crawl_config = {
    }

    def __init__(self):
        self.base_url = 'https://mm.taobao.com/json/request_top_list.htm?page='
        self.page_num = 1
        self.total_num = 5

    @every(minutes=24 * 60)
    def on_start(self):
        while self.page_num <= self.total_num:
            url = self.base_url + str(self.page_num)
            #print url
            self.crawl(url, callback=self.index_page)
            self.page_num += 1

    @config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('.lady-name').items():
            self.crawl(each.attr.href, callback=self.detail_page, fetch_type='js')




    def detail_page(self, response):
        url = 'https:' + response.doc('.mm-p-domain-info li>span').text()
        self.crawl(url, callback=self.domain_page)


    def domain_page(self, response):
        name = response.doc('.mm-p-model-info-left-top dd > a').text()
        self.Deal = Deal()
        dir_path = self.Deal.mkDir(name)
        brief = response.doc('.mm-aixiu-content').text()
        if dir_path:
            imgs = response.doc('.mm-aixiu-content img').items()
            count = 1
            self.Deal.saveBrief(brief, dir_path, name)
            for img in imgs:
                url = img.attr.src
                if url:
                    extension = self.Deal.getExtension(url)
                    file_name = name + str(count) + '.' + extension
                    count += 1
                    self.crawl(img.attr.src, callback=self.save_img,
                               save={'dir_path': dir_path, 'file_name': file_name})
    @config(priority=2)
    def save_img(self, response):
        self.Deal = Deal()
        content = response.content
        dir_path = response.save['dir_path']
        file_name = response.save['file_name']
        file_path_name = dir_path + '/' + file_name
        self.Deal.saveImg(content, file_path_name)



import os

DIR_PATH = '/home/ec/Downloads'

class Deal:
    def __init__(self):
        self.path = DIR_PATH
        if not self.path.endswith('/'):
            self.path = self.path + '/'
        if not os.path.exists(self.path):
            os.makedirs(self.path)

    def mkDir(self, path):
        path = path.strip()
        dir_path = self.path + path
        exists = os.path.exists(dir_path)
        if not exists:
            os.makedirs(dir_path)
            return dir_path
        else:
            return dir_path

    def saveImg(self, content, filename):
        f = open(filename, 'wb')
        f.write(content)
        f.close()

    def saveBrief(self, content, dir_path, name):
        file_name = dir_path + "/" + name + ".txt"
        with open(file_name, "wb") as f:
            f.write(content.encode('utf-8'))

    def getExtension(self, url):
        extension = url.split('.')[-1]
        return extension
